export {default as DashBoardPage} from "./DashBoardPage"
export {default as AddUser} from "./AddUser"
export {default as ActiveInvestmentPage} from "./ActiveInvestmentPage"
export {default as ActiveUsersPage} from "./ActiveUsersPage"
export {default as CompletedInvestmentPage} from "./CompletedInvestmentPage"
export {default as PendingWithdrawPage} from "./PendingWithdrawPage"
export {default as CompletedWithdrawalPage} from "./CompletedWithdrawalPage"
export {default as FailedWithdralPage} from "./FailedWithdralPage"
